apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - prune-test-service.yaml
  - ../../base

namespace: baba-app

images:
  - name: baba-app-backend
    newName: 406312601212.dkr.ecr.us-east-1.amazonaws.com/baba-app-dev-backend
    digest: sha256:88f9c5203ea301c780029f7b9a62d3c0777d4d037ed7738093777b723d2a7a74

  - name: baba-app-frontend
    newName: 406312601212.dkr.ecr.us-east-1.amazonaws.com/baba-app-dev-frontend
    digest: sha256:de401212938d47baddf5432aa54c6ce0ce0eb193f488706126003163a898f59b

labels:
  - pairs:
      app.kubernetes.io/environment: dev