apiVersion: v1
kind: Namespace
metadata:
  name: baba-app
  labels:
    app.kubernetes.io/name: baba-app
    app.kubernetes.io/part-of: baba-app
    app.kubernetes.io/environment: dev
    app.kubernetes.io/managed-by: argocd