apiVersion: v1
kind: Service
metadata:
  name: baba-app-prune-test
  namespace: baba-app
  labels:
    app.kubernetes.io/name: baba-app-prune-test
    app.kubernetes.io/part-of: baba-app
    app.kubernetes.io/environment: dev
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP