apiVersion: v1
kind: Service
metadata:
  name: baba-app-backend
  labels:
    app.kubernetes.io/name: baba-app-backend
    app.kubernetes.io/part-of: baba-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: baba-app-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP