apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baba-app-identity-dev
  namespace: argocd
spec:
  project: baba-app

  source:
    repoURL: https://github.com/mkdevops89/baba-app.git
    targetRevision: main
    path: 09-identity/kubernetes-rbac

  destination:
    server: https://kubernetes.default.svc
    namespace: baba-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=false